# Form implementation generated from reading ui file 'dialog_new.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, QtSql
import design.resources
from connection import Data


class Ui_Dialog_New(object):
    def setupUi(self, Dialog, table):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 487)
        Dialog.setStyleSheet("background-color: #A8D8EA;\n"
"font-family: arial rounded mt bold;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setStyleSheet("background-color: #EAFFD0;\n"
"border-radius: 10px;\n"
"border: 1px solid #AA96DA;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_name = QtWidgets.QLabel(parent=self.frame)
        self.label_main_name.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("arial rounded mt 13")
        font.setPointSize(20)
        font.setBold(True)
        self.label_main_name.setFont(font)
        self.label_main_name.setStyleSheet("background-color: #AA96DA;\n"
"border-radius: 10px;\n"
"color: #FCE38A;\n"
"border: 1px solid white;")
        self.label_main_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_main_name.setObjectName("label_main_name")
        self.verticalLayout.addWidget(self.label_main_name)
        self.combox_choose_table = QtWidgets.QComboBox(parent=self.frame)
        self.combox_choose_table.setMinimumSize(QtCore.QSize(0, 30))
        self.combox_choose_table.setStyleSheet("")
        self.combox_choose_table.setObjectName("combox_choose_table")
        self.combox_choose_table.addItem("")
        self.combox_choose_table.addItem("")
        self.combox_choose_table.addItem("")
        self.combox_choose_table.addItem("")
        self.verticalLayout.addWidget(self.combox_choose_table)

        self.edit_ui = Data()
        self.column = self.edit_ui.select_column_name(table)
        self.dict_obj_name = {}
        for i in range(len(self.column)):
            if self.column[i] == 'int':
                self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
                self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.lineEdit.setObjectName(f"lineEdit_{i+1}")
                self.dict_obj_name[f"lineEdit_{i+1}"] = self.column[i]
                setattr(self, f"lineEdit_{i+1}", self.lineEdit)
                self.verticalLayout.addWidget(self.lineEdit)
            elif self.column[i] == 'nvarchar':
                self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
                self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.lineEdit.setObjectName(f"lineEdit_{i+1}")
                self.dict_obj_name[f"lineEdit_{i+1}"] = self.column[i]
                setattr(self, f"lineEdit_{i+1}", self.lineEdit)
                self.verticalLayout.addWidget(self.lineEdit)

        '''self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)'''
        self.btn_new_entry = QtWidgets.QPushButton(parent=self.frame)
        self.btn_new_entry.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("arial rounded mt 13")
        font.setBold(True)
        self.btn_new_entry.setFont(font)
        self.btn_new_entry.setStyleSheet("QPushButton {\n"
"background-color: #AA96DA;\n"
"border-radius: 10px;\n"
"color: #FCE38A;\n"
"font-size: 14px;\n"
"border: 1px solid white\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #F38181;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EAFFD0;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/add_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_new_entry.setIcon(icon)
        self.btn_new_entry.setIconSize(QtCore.QSize(24, 24))
        self.btn_new_entry.setObjectName("btn_new_entry")
        self.verticalLayout.addWidget(self.btn_new_entry)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.combox_choose_table.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_main_name.setText(_translate("Dialog", "Добавление записи"))
        self.combox_choose_table.setPlaceholderText(_translate("Dialog", "Выбери таблицу"))
        self.combox_choose_table.setItemText(0, _translate("Dialog", "Element 1"))
        self.combox_choose_table.setItemText(1, _translate("Dialog", "Element 2"))
        self.combox_choose_table.setItemText(2, _translate("Dialog", "Element 3"))
        self.combox_choose_table.setItemText(3, _translate("Dialog", "Element 4"))
        self.btn_new_entry.setText(_translate("Dialog", "Добавить"))
