# Form implementation generated from reading ui file 'dialog_edit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, QtSql
import design.resources
from connection import Data


class Ui_Dialog_Edit(object):
    def setupUi(self, Dialog, table, id):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 487)
        Dialog.setStyleSheet("background-color: #A8D8EA;\n"
"font-family: arial rounded mt bold;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setStyleSheet("background-color: #EAFFD0;\n"
"border-radius: 10px;\n"
"border: 1px solid #AA96DA;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_name = QtWidgets.QLabel(parent=self.frame)
        self.label_main_name.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("arial rounded mt 13")
        font.setPointSize(20)
        font.setBold(True)
        self.label_main_name.setFont(font)
        self.label_main_name.setStyleSheet("background-color: #AA96DA;\n"
"border-radius: 10px;\n"
"color: #FCE38A;\n"
"border: 1px solid white;")
        self.label_main_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_main_name.setObjectName("label_main_name")
        self.verticalLayout.addWidget(self.label_main_name)

        self.edit_ui = Data()
        self.data_type = self.edit_ui.select_data_type(table)
        self.column = self.edit_ui.select_column_name(table)
        self.entry = self.edit_ui.select_current_entry(table, id, self.column)
        print(self.entry)
        self.dict_obj_name = {}
        for i in range(1, len(self.data_type)):
            if self.data_type[i] == 'int' or self.data_type[i] == 'money' or self.data_type[i] == 'bigint' or self.data_type[i] == 'smallint' or self.data_type[i] == 'real' or self.data_type[i] == 'float' or self.data_type[i] == 'tinyint' or self.data_type[i] == 'bit' or self.data_type[i] == 'decimal' or self.data_type[i] == 'smallmoney' or self.data_type[i] == 'float' or self.data_type[i] == 'numeric':
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName(f"horizontalLayout_{i}")
                self.label = QtWidgets.QLabel(parent=self.frame)
                self.label.setMinimumSize(QtCore.QSize(100, 0))
                self.label.setStyleSheet("background-color: #A8D8EA;\n"
                                         "border: 1px solid gray;")
                self.label.setObjectName(f"label_{i}")
                self.horizontalLayout.addWidget(self.label)
                self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
                self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.lineEdit.setObjectName(f"lineEdit_{i}")
                self.dict_obj_name[f"lineEdit_{i}"] = self.data_type[i]
                setattr(self, f"lineEdit_{i}", self.lineEdit)
                self.horizontalLayout.addWidget(self.lineEdit)
                self.verticalLayout.addLayout(self.horizontalLayout)
                _translate = QtCore.QCoreApplication.translate
                self.label.setText(_translate("Dialog", self.column[i]))
                self.lineEdit.setPlaceholderText(_translate("Dialog", f"Введите {self.column[i]}"))
                self.lineEdit.setText(_translate("Dialog", str(self.entry[i])))
            elif self.data_type[i] == 'datetime' or self.data_type[i] == 'datetime2' or self.data_type[i] == 'datetimeoffset' or self.data_type[i] == 'smalldatetime':
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName(f"horizontalLayout_{i}")
                self.label = QtWidgets.QLabel(parent=self.frame)
                self.label.setMinimumSize(QtCore.QSize(100, 0))
                self.label.setStyleSheet("background-color: #A8D8EA;\n"
                                         "border: 1px solid gray;")
                self.label.setObjectName(f"label_{i}")
                self.horizontalLayout.addWidget(self.label)
                self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.frame)
                self.dateTimeEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.dateTimeEdit.setObjectName(f"dateTimeEdit_{i}")
                self.dict_obj_name[f"dateTimeEdit_{i}"] = self.data_type[i]
                setattr(self, f"dateTimeEdit_{i}", self.dateTimeEdit)
                self.horizontalLayout.addWidget(self.dateTimeEdit)
                self.verticalLayout.addLayout(self.horizontalLayout)
            elif self.data_type[i] == 'date':
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName(f"horizontalLayout_{i}")
                self.label = QtWidgets.QLabel(parent=self.frame)
                self.label.setMinimumSize(QtCore.QSize(100, 0))
                self.label.setStyleSheet("background-color: #A8D8EA;\n"
                                         "border: 1px solid gray;")
                self.label.setObjectName(f"label_{i}")
                self.horizontalLayout.addWidget(self.label)
                self.dateEdit = QtWidgets.QDateEdit(parent=self.frame)
                self.dateEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.dateEdit.setObjectName(f"dateEdit_{i}")
                self.dict_obj_name[f"dateEdit_{i}"] = self.data_type[i]
                setattr(self, f"dateEdit_{i}", self.dateEdit)
                self.horizontalLayout.addWidget(self.dateEdit)
                self.verticalLayout.addLayout(self.horizontalLayout)
            elif self.data_type[i] == 'time':
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName(f"horizontalLayout_{i}")
                self.label = QtWidgets.QLabel(parent=self.frame)
                self.label.setMinimumSize(QtCore.QSize(100, 0))
                self.label.setStyleSheet("background-color: #A8D8EA;\n"
                                         "border: 1px solid gray;")
                self.label.setObjectName(f"label_{i}")
                self.horizontalLayout.addWidget(self.label)
                self.timeEdit = QtWidgets.QTimeEdit(parent=self.frame)
                self.timeEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.timeEdit.setObjectName(f"timeEdit_{i}")
                self.dict_obj_name[f"timeEdit_{i}"] = self.data_type[i]
                setattr(self, f"timeEdit_{i}", self.timeEdit)
                self.horizontalLayout.addWidget(self.timeEdit)
                self.verticalLayout.addLayout(self.horizontalLayout)
            elif self.data_type[i] == 'text' or self.data_type[i] == 'ntext':
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName(f"horizontalLayout_{i}")
                self.label = QtWidgets.QLabel(parent=self.frame)
                self.label.setMinimumSize(QtCore.QSize(100, 0))
                self.label.setStyleSheet("background-color: #A8D8EA;\n"
                                         "border: 1px solid gray;")
                self.label.setObjectName(f"label_{i}")
                self.horizontalLayout.addWidget(self.label)
                self.textEdit = QtWidgets.QTextEdit(parent=self.frame)
                self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
                self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
                self.textEdit.setObjectName(f"textEdit_{i}")
                self.dict_obj_name[f"textEdit_{i}"] = self.data_type[i]
                setattr(self, f"textEdit_{i}", self.textEdit)
                self.horizontalLayout.addWidget(self.textEdit)
                self.verticalLayout.addLayout(self.horizontalLayout)
                _translate = QtCore.QCoreApplication.translate
                self.label.setText(_translate("Dialog", self.column[i]))
                self.lineEdit.setPlaceholderText(_translate("Dialog", f"Введите {self.column[i]}"))
                self.textEdit.setText(_translate("Dialog", self.entry[i]))
            else:
                self.horizontalLayout = QtWidgets.QHBoxLayout()
                self.horizontalLayout.setObjectName(f"horizontalLayout_{i}")
                self.label = QtWidgets.QLabel(parent=self.frame)
                self.label.setMinimumSize(QtCore.QSize(100, 0))
                self.label.setStyleSheet("background-color: #A8D8EA;\n"
                                         "border: 1px solid gray;")
                self.label.setObjectName(f"label_{i}")
                self.horizontalLayout.addWidget(self.label)
                self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
                self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
                self.lineEdit.setObjectName(f"lineEdit_{i}")
                self.dict_obj_name[f"lineEdit_{i}"] = self.data_type[i]
                setattr(self, f"lineEdit_{i}", self.lineEdit)
                self.horizontalLayout.addWidget(self.lineEdit)
                self.verticalLayout.addLayout(self.horizontalLayout)
                _translate = QtCore.QCoreApplication.translate
                self.label.setText(_translate("Dialog", self.column[i]))
                self.lineEdit.setPlaceholderText(_translate("Dialog", f"Введите {self.column[i]}"))
                self.lineEdit.setText(_translate("Dialog", self.entry[i]))

        self.btn_edit_entry = QtWidgets.QPushButton(parent=self.frame)
        self.btn_edit_entry.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("arial rounded mt 13")
        font.setBold(True)
        self.btn_edit_entry.setFont(font)
        self.btn_edit_entry.setStyleSheet("QPushButton {\n"
"background-color: #AA96DA;\n"
"border-radius: 10px;\n"
"color: #FCE38A;\n"
"font-size: 14px;\n"
"border: 1px solid white\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #F38181;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EAFFD0;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/edit_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_edit_entry.setIcon(icon)
        self.btn_edit_entry.setIconSize(QtCore.QSize(24, 24))
        self.btn_edit_entry.setObjectName("btn_edit_entry")
        self.verticalLayout.addWidget(self.btn_edit_entry)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_main_name.setText(_translate("Dialog", "Изменение записи"))
        self.btn_edit_entry.setText(_translate("Dialog", "Изменить"))
